In [1]:
import numpy as np
import pandas as pd 

In [7]:
print(s1.index.values) ###showing the different index qualifications

[2016 2017 2018 2019 2020]


In [8]:
s1.values #showing the values as an array

array([4.1, 5.2, 6.3, 7.4, 8.5])

In [10]:
s2.loc[2019] ##looking at a specific value
s2.loc[2018:2019] ##more than one value, but not all --> a slice!

2018    34.5
2019    34.0
Name: Salinity, dtype: float64

In [12]:
#changing the 2019 and 2020 temperature and salinity - good 4 catching/fixing errors/. 
s1.loc[2019] = 6.4 #changing one value.

#index by yearm assign new value
s1.loc[2020] = 7.5
display(s1)

2016    4.1
2017    5.2
2018    6.3
2019    6.4
2020    7.5
Name: Temperature, dtype: float64

In [14]:
display(s1)
display(s2)

2016    4.1
2017    5.2
2018    6.3
2019    6.4
2020    7.5
Name: Temperature, dtype: float64

2016    35.5
2017    35.0
2018    34.5
2019    34.0
2020    33.5
Name: Salinity, dtype: float64

In [16]:
pd.concat([s1,s2]) ## combining via column

2016     4.1
2017     5.2
2018     6.3
2019     6.4
2020     7.5
2016    35.5
2017    35.0
2018    34.5
2019    34.0
2020    33.5
dtype: float64

In [19]:
env_diff = pd.concat([s1,s2], axis=1) #combine via row, separates into whole new thingy!

In [21]:
env_diff.loc[2019:2020] #noe getting just what we wanna

Temperature  Salinity
2019          6.4      34.0
2020          7.5      33.5

In [25]:
##finding mean temperatures across all years 
temp=np.mean(env_diff['Temperature']) #remember, spelling has to be EXACT
salt=np.mean(env_diff['Salinity'])


34.5

In [24]:
#just salinity graph
env_diff.Salinity

2016    35.5
2017    35.0
2018    34.5
2019    34.0
2020    33.5
Name: Salinity, dtype: float64

In [28]:
#mean 2018 -2020
np.mean(env_diff.loc[2018:2020,'Temperature'])
np.mean(env_diff.loc[2018:2020,'Salinity'])

34.0

In [31]:
##x-array demo

import xarray as xr

In [34]:
filepath = 'zinser_ground_truth.nc'
growth = xr.open_dataset(filepath, decode_times=False)
display(growth)

<xarray.Dataset>
Dimensions:             (abundance_time: 25, division_time: 24,
                         carbonloss_time: 24, carbonfix_time: 25)
Coordinates:
  * abundance_time      (abundance_time) int64 0 2 4 6 8 10 ... 40 42 44 46 48
  * division_time       (division_time) int64 1 3 5 7 9 11 ... 37 39 41 43 45 47
  * carbonloss_time     (carbonloss_time) int64 1 3 5 7 9 11 ... 39 41 43 45 47
  * carbonfix_time      (carbonfix_time) int64 1 3 5 7 9 11 ... 41 43 45 47 49
Data variables: (12/14)
    abundance           (abundance_time) float64 ...
    abundance_sd        (abundance_time) float64 ...
    division            (division_time) float64 ...
    division_sd         (division_time) float64 ...
    dailydivision       float64 ...
    dailydivision_sd    float64 ...
    ...                  ...
    dailycarbonloss     float64 ...
    dailycarbonloss_sd  float64 ...
    carbonfix           (carbonfix_time) float64 ...
    carbonfix_sd        (carbonfix_time) float64 ...
    dailycarbonfix      float64 ...
    dailycarbonfix_sd   float64 ...
Attributes:
    created_by:               propagate_uncertainty.ipynb
    correct_abundance_mean:   1
    scale_error_with_signal:  1
    loss_formulation:         cellsizebased

In [38]:
#looking at just values 
growth['abundance']

#look at hours 0,2,4
growth.sel(abundance_time=[0,2,4]).abundance_sd.values

array([1217726.78359411, 1263257.61124618, 1272713.84314283])

In [40]:
#making a plot, carbonloss

y = growth['carbonloss'].coords.values
x = growth['carbonloss'].values

import matplotlib.pyplot as ply
fig,axs = plt.subplot(figsize=(10,6)
axs.plot(x,y)

SyntaxError: '(' was never closed (2891214703.py, line 7)